### GET ALL BUSES
GET http://localhost:8080/api/v1/buses

### GET ONE BUS
GET http://localhost:8080/api/v1/buses/1

### DELETE ONE BUS
DELETE http://localhost:8080/api/v1/buses/3

### CREATE ONE BUS
POST http://localhost:8080/api/v1/buses
Content-Type: application/json

{
  "countryNumber": "672901",
  "boardingNumber": "AK 4212 JI"
}

### UPDATE ONE BUS
PUT http://localhost:8080/api/v1/buses
Content-Type: application/json

{
  "id": "2",
  "countryNumber": "294914",
  "boardingNumber": "CE 3354 MO"
}

### GREETING ADMIN
GET http://localhost:8080/api/v1/buses/hello/admin

### GREETING USER
GET http://localhost:8080/api/v1/buses/hello/user

### GREETING UNKNOWM
GET http://localhost:8080/api/v1/buses/hello/unknown







